### PR TITLE
Remove annotations

### PR DESCRIPTION
**Pull request by burmjeff**
Removed annotations and some other small changes.

### CODE REVIEW

**Comment by Zaphod-Beeblebrox** [comment]
OK .. This now compiles, but when running I get a FC with the following log:

08-21 14:45:35.982: E/AndroidRuntime(944): FATAL EXCEPTION: main
08-21 14:45:35.982: E/AndroidRuntime(944): Process: com.bonovo.bonovohandle, PID: 944
08-21 14:45:35.982: E/AndroidRuntime(944): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.bonovo.bonovohandle/com.bonovo.bonovohandle.AppListActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class android.support.v7.widget.RecyclerView
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.app.ActivityThread.access$800(ActivityThread.java:135)
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.os.Handler.dispatchMessage(Handler.java:102)
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.os.Looper.loop(Looper.java:136)
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.app.ActivityThread.main(ActivityThread.java:5017)
08-21 14:45:35.982: E/AndroidRuntime(944):  at java.lang.reflect.Method.invokeNative(Native Method)
08-21 14:45:35.982: E/AndroidRuntime(944):  at java.lang.reflect.Method.invoke(Method.java:515)
08-21 14:45:35.982: E/AndroidRuntime(944):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
08-21 14:45:35.982: E/AndroidRuntime(944):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
08-21 14:45:35.982: E/AndroidRuntime(944):  at dalvik.system.NativeStart.main(Native Method)
08-21 14:45:35.982: E/AndroidRuntime(944): Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class android.support.v7.widget.RecyclerView
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.view.LayoutInflater.createView(LayoutInflater.java:620)
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
08-21 14:45:35.982: E/AndroidRuntime(944):  at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:298)
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.app.Activity.setContentView(Activity.java:1937)
08-21 14:45:35.982: E/AndroidRuntime(944):  at com.bonovo.bonovohandle.AppListActivity.onCreate(AppListActivity.java:31)
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.app.Activity.performCreate(Activity.java:5242)
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
08-21 14:45:35.982: E/AndroidRuntime(944):  ... 11 more
08-21 14:45:35.982: E/AndroidRuntime(944): Caused by: java.lang.reflect.InvocationTargetException
08-21 14:45:35.982: E/AndroidRuntime(944):  at java.lang.reflect.Constructor.constructNative(Native Method)
08-21 14:45:35.982: E/AndroidRuntime(944):  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.view.LayoutInflater.createView(LayoutInflater.java:594)
08-21 14:45:35.982: E/AndroidRuntime(944):  ... 22 more
08-21 14:45:35.982: E/AndroidRuntime(944): Caused by: java.lang.NoClassDefFoundError: android.support.v4.widget.ScrollerCompatGingerbread
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.support.v4.widget.ScrollerCompat$ScrollerCompatImplGingerbread.createScroller(ScrollerCompat.java:161)
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.support.v4.widget.ScrollerCompat.<init>(ScrollerCompat.java:280)
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.support.v4.widget.ScrollerCompat.create(ScrollerCompat.java:265)
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.support.v7.widget.RecyclerView$ViewFlinger.<init>(RecyclerView.java:4027)
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.support.v7.widget.RecyclerView.<init>(RecyclerView.java:380)
08-21 14:45:35.982: E/AndroidRuntime(944):  at android.support.v7.widget.RecyclerView.<init>(RecyclerView.java:465)
08-21 14:45:35.982: E/AndroidRuntime(944):  ... 25 more

**Comment by burmjeff** [comment]
Sorry for the delay I finally got a chance to update all of this and make sure it's working.

It should be good now with commit 3e5b20e

**Comment by DwaineGarden** [comment]
I'm still getting weird compile errors.

**Comment by burmjeff** [comment]
@DwaineGarden 

Can you make sure that you fully wiped bonovohandle build files and included commit 3e5b20e.

I just completely wiped my entire build folder, built it again, and it went ok for me.

**Comment by DwaineGarden** [comment]
Ok.  I'll try that
On Sep 6, 2016 10:18 PM, burmjeff notifications@github.com wrote:@DwaineGarden 

Can you make sure that you fully wiped bonovohandle build files and included commit 3e5b20e.

I just completely wiped my entire build folder, built it again, and it went ok for me.

**Comment by burmjeff** [comment]
If you don't want to have to build everything from scratch... Here is what I do before building when I'm testing changes:

 rm -r out/target/product/rk3188/system/app/BonovoHandle.apk
 rm -r out/target/product/rk3188/obj/APPS/BonovoHandle_intermediates/
 rm -r out/target/common/obj/APPS/BonovoHandle_intermediates/

**Comment by DwaineGarden** [comment]
I can confirm that this patch fixes compiling issues that I was experiencing.  Can we get this committed?

**Comment by DwaineGarden** [comment]
Thanks.....

**Pull request merged**
