### PR TITLE
Radio Changes

### PR DESCRIPTION
**Pull request by burmjeff**
Updated parts to 1.3.4
Added a layout selection in settings so you can choose between layouts used.

### CODE REVIEW

**Comment by DwaineGarden** [comment]
Wooo...  The changes for the radio application of 1.3.4.    I actually like the radio widget.

**Comment by jamesgol** [comment]
Is this just all the changes pulled in from the latest radio code they gave out to us?  I'd like to get it merged in but want to make sure first that none of the other changes @Zaphod-Beeblebrox already made don't conflict.

When I get a chance I'll test this out.

**Comment by burmjeff** [comment]
Here are basically the major changes (removals) from current master to help save you time.
- Radioactivity: commented out btnimport
- Radioservice: No more RemoteControlClient and MediaMetadata. "updatePlaybackTitle()" has changed completely.
- Removed some redundant/unused resources.
- Split up old layout and new layout and created another preference setting so you can choose which one you want to use.

**Comment by lkernan** [comment]
I haven't compiled or tried this yet, but this one bothers me:
"No more RemoteControlClient and MediaMetadata. "updatePlaybackTitle()" has changed completely."

why?  I'm guessing this will stop the radio appearing in AutoMate at the least.

**Comment by Zaphod-Beeblebrox** [comment]
This definitely looks to break RemoteControlClient.  Possibly audio ducking as well.

I wouldn't merge this as is.  We need those two functions

**Pull request closed without merging**
