### PR TITLE
Connected standby mode

### PR DESCRIPTION
**Pull request by lkernan**
Adds support to Bonovohandle to delay the activation of airplane mode in standby.

Also adds an option to the MCU Update app standby page to configure the delay time.

### CODE REVIEW

**Comment by jamesgol** [comment]
Awesome.   This was on my todo list,  ut been crazy busy lately.

**Comment by lkernan** [comment]
It wasn't something i needed until I fixed my Wifi reception issues.  
Now I can actually use it!

**Comment by jamesgol** [comment]
Finally got a chance to look at the code.  I think 5 min, 15 min, 30min, 60min, forever/infinite would be better times.  

I was hoping to switch the regular standby to a seekbar and give more choices but haven't had the chance for that.  I never was happy with the times bonovo picked.  I think having a 4 hour, 6 hour, 8 hour, 16 hour, 18 hour would be reasonable.

**Comment by lkernan** [comment]
I wasn't so sure about the power usage, if you think that longer times would be ok i'll change it. 
Personally i'd use if for small things like syncing mail after getting home, etc. 

I'm going to write up a patch tonight anyway.  I used milliseconds because that's what the handler used.  I didn't think about it until committing and realised that it probably should be at least seconds.

**Comment by jamesgol** [comment]
Another option would be to stay consistent with what Bonovo does (which IMO is pretty dumb, but at least it would be consistent) and use 10 minute intervals.  I'd use 65535 for forever/infinite.

I know my plan was to have it sync music/videos which could take a while if there are a lot of them.

**Comment by lkernan** [comment]
Hopefully this should cover all bases.  There might be one or two that don't need to be there, but I don't see the harm in leaving them.

// Connected Standby delay times (in minutes)
private final int CS_OFF= 0;
private final int CS_FIVE_MIN= 5;
private final int CS_TEN_MIN= 10;
private final int CS_HALF_HOUR= 30;
private final int CS_ONE_HOUR= 60;
private final int CS_FOUR_HOURS= 240;
private final int CS_EIGHT_HOURS= 480;
private final int CS_HALF_DAY= 720;
private final int CS_ONE_DAY= 1440;
private final int CS_INFINITE= 65535;

**Comment by Zaphod-Beeblebrox** [comment]
Why isn't this just a boolean setting (ie, leave network on/off during sleep), and the sleep timer does the rest?  Do we really need fine-grain control over sleep and network separately?

**Comment by lkernan** [comment]
I might have the sleep set at 2 hours but only want it to sync email quickly when I get home.  
Why would I leave wifi on wasting battery for 2 hours too?

**Comment by Zaphod-Beeblebrox** [comment]
I thought initial tests suggested battery draw was not an issue with network on?

**Comment by lkernan** [comment]
I still have my doubts.

**Comment by Zaphod-Beeblebrox** [comment]
No worries.  If you like it, and want to code it, go for it :)  I might could see where a sleep timer of 2 days, and a network timer somewhat lower could benefit battery issues,  but for your average  1 to 4 hour sleep timer, I don't see it being an issue.

**Comment by lkernan** [comment]
Would it help if I changed the options to: 
Off
Ten Minutes
One Hour
Half Day
One Day
Always while sleeping

**Comment by Zaphod-Beeblebrox** [comment]
I haven't look specifically at the code/options.  As James mentioned, it might be nice to have this as a slider rather than checkboxes.  And the options for Network timer should mirror the sleep timer (even if it means changing the sleep timer options to something more logical for us).
And lastly, the network timer should not allow values greater than the sleep timer :)

**Comment by jamesgol** [comment]
The power draw is low but it is still high enough that I wouldn't want it left on the whole time.  If some app was especially chatty it could keep transmitting and potentially wear down the battery especially if someone has an older battery in the winter.

**Pull request merged**
