### PR TITLE
Fixes to connected standby mode

### PR DESCRIPTION
**Pull request by lkernan**
- Adjust timeout options due to feedback.
- Change intent to set delay to use minutes instead of milliseconds

### CODE REVIEW

**Comment by jamesgol** [comment]
Curious what the reason for using two different shared storage locations are?  I'd think that having the mcuupdate_and_setting app save the value and then having bonovoHandle retrieve from that same source is ideal.  

Was looking into why the value wasn't saved and noticed this.

**Comment by lkernan** [comment]
To be honest i'd rather MCUupdate didn't save it at all, it should all be handled by bonovohandle and MCUUpdate gets the current value from there.  
It was that i couldn't get MCUUpdate to read the preference saved by handle and I got sidetracked.

**Comment by jamesgol** [comment]
I'd actually say that MCUupdate is the place it should be saved because the get/set is more of a user interaction vs all the system interaction that BonovoHandle does.

I'd guess that the issue with reading across apps was because the preference is set to private instead of world readable.

**Comment by lkernan** [comment]
"I'd guess that the issue with reading across apps was because the preference is set to private instead of world readable."

I know Bonovo do it, but we shouldn't be copying their bad ideas.  There's a reason there are plenty of warnings saying not to do that.

**Comment by lkernan** [comment]
Besides, it's only in McuUpdate so it shows the current value.  We could remove it from there and do no harm.  
I'm interested to see how the wider testing goes, becuase i'm getting so fed up with this i'm ready to revert it back out for now. In my car it works probably one in five times which is just odd.

The serial logs show that when it fails, the Android box is reporting status normal way too soon before the MCU is ready. On a normal start the Android box reports ready after the MCU has initialized the various hardware devices.

**Comment by jamesgol** [comment]
I'm pretty sure the weird screen sleep issues aren't related to this.  I'm pretty sure I noticed it before you started working on it, it might even have started when upgrading to MCUv41.  I haven't had a chance to do some serious testing to see when the issue started.

**Comment by lkernan** [comment]
Oh crap, now you mention it, i did upgrade to v41 only last week when I broke my SWC......
Will try flashing back to v40 now.  Thanks for mentioning that

**Comment by jamesgol** [comment]
In the v41 release notes there is "< 3 > increases if monitoring Andrews is abnormally wake in standby ."  whatever the hell that means.

If we can confirm that it's an issue related to that we can trace exactly which serial commands are sent/received and figure out what to do to duplicate them.

**Comment by lkernan** [comment]
Ok, flashed back to v40 and it's done 3 out of 3 properly so far. 
I wish I'd thought of that, looks like for now it's safer to stick with MCU v40.  

My guess is we'll need to look at their latest builds to find out what they've added to keep the MCU watchdog happy.

**Comment by jamesgol** [comment]
I'm not convinced anymore that v40 vs v41 matters.  Still need to keep digging though. 

It definitely seems like having USB hooked up makes the problem worse.  Probably need to switch to logcat over tcp instead of USB.

**Comment by lkernan** [comment]
All my testing in the car is with no USB devices connected.  I can clearly see the standby problems with v41 and they consistently go away when i got back to v40.  Switching back to v41 brings them right back.

I've already identified one change in Newsmy's version 1.1.9 bonovoHandle by running strace over it.  They've gone from writing the standby signal once to repeating it three times on both sleep and wakeup.  
That hasn't totally solved the problem for me but it has reduced it a bit.  Still looking into what else has changed.

**Comment by lkernan** [comment]
Of course, it's also possible we're chasing down a bug that they will just fix in the next version..

**Comment by jamesgol** [comment]
I saw that change also looking at the serial lines.  The 0x95 commands are each sent 3 times.

**Pull request merged**
