### PR TITLE
More work on RadioActivity.java (should be done?)

### PR DESCRIPTION
**Pull request by asidorowicz**

### CODE REVIEW

**Comment by Zaphod-Beeblebrox** [comment]
I'll try to work on this tonight and see if we can at least get it to compile.  I want to start working on adding functionality to this app (and changing the layout), but I don't want to do so until we have a good working base that we can call '1.1.4'.

The one thing I would like to figure out (and I don't know how), is all of these integer inserts were originally mapped to STATIC's.  While our code might work, it's going to be difficult to read.  I would like to figure out how to map these back to the STATIC's,  and what they mean.

**Comment by asidorowicz** [comment]
I'm gonna go over the integer inserts again once I have the full source figured out. I'm fairly confident we can figure out the intents :) RadioService.java will be my next target

**Comment by Zaphod-Beeblebrox** [comment]
I think I have already fixed RadioService in my commit.

Mike Wilson
Senior Damage Appraiser

ACES Appraisal Group, Inc.
Office: 540-268-5558 x 201 / Fax: 540-268-1167
P.O. Box 300 Christiansburg, VA 24068
http://www.acesappraisal.com

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. ACES Appraisal
Group is not responsible for errors or omissions in this message and denies
any responsibility for any damage arising from the use of e-mail. Any
opinion and other statement contained in this message and any attachment
are solely those of the author and do not necessarily represent those of
the company.

**Comment by asidorowicz** [comment]
There were more changes to RadioService - I think I have them down
The problem I'm currently facing is I can't commit to this branch - permission denied? Anxious to push those changes :)

**Comment by Zaphod-Beeblebrox** [comment]
I added you to the repo so you should be able to push now.  Just don't overwrite the changes I did last night :)

**Comment by asidorowicz** [comment]
I pulled them first, no worries! I moved the location of the method you recreated to correspond closer to the original source (apkstudio gives us the line numbers)

**Comment by Zaphod-Beeblebrox** [comment]
Awesome.  Why don't you add me on hangouts to make communication easier  (m   wilson    at  aces  appraisal   dot   com)

**Pull request merged**
