### PR TITLE
Merge 1.3.4 Changes + Layout Selector

### PR DESCRIPTION
**Pull request by burmjeff**
- Merged 1.3.4 changes
- Layout selector (Choose new or old layout)
- Made layouts more scalable

### CODE REVIEW

**Comment by burmjeff** [comment]
You guys are right I don't know what I was thinking.  I have now properly merged 1.3.4 with previous changes intact.

**Comment by jamesgol** [comment]
Thanks, Hopefully I'll have a chance to review this and try it out in the next few days.

**Comment by DwaineGarden** [comment]
James did the changes look good?

**Comment by jamesgol** [comment]
Sorry I haven't had a chance to work on any of the carpad stuff lately.  So swamped right now that I haven't been able to keep up with the xda forums

**Comment by red13dotnet** [comment]
Tested and verified

**Pull request merged**
