### PR TITLE
AirConditioning has now been updated to 1.1.4

### PR DESCRIPTION
**Pull request by asidorowicz**
Here's the diff I managed to create between 1.0.9 and the 1.1.4 release

### CODE REVIEW

**Comment by Zaphod-Beeblebrox** [comment]
You are so incredibly awesome for helping with this!  This is the type of involvement I've wanted/need on this project.
It might be this weekend before I get a chance to pull the patch and merge/test/pull, etc.  But please keep them coming!

**Comment by Zaphod-Beeblebrox** [comment]
I've started to go through and fix some compile errors (mostly small stuff so far, scope of variable definitions, etc).  But running into a lot of resource issues in the radio app.  Before I bang my head against the wall too much,  how far into the radio port were you?  I don't want to us to work overtop each other.

**Comment by asidorowicz** [comment]
Hey, I was a little busy in the past couple of days, but am still working on the ports
I have focused on the RadioActivity class in the radio app (think I'm done?)
I have not been able to construct a build environment yet, but that should come soon. If you have any comments, let me know

**Comment by Zaphod-Beeblebrox** [comment]
Hey.  Before you work any more on the radio app, take a look at the repo.
I created a new branch (114update).  I've had to fix a lot of little
things, and I still have a few small resource errors, but it's getting very
close to compiling (and then we start working on live testing :))

**Comment by asidorowicz** [comment]
I can't seem to find the branch in https://github.com/Zaphod-Beeblebrox/packages_apps_BonovoApps, is it somewhere else?

**Comment by Zaphod-Beeblebrox** [comment]
It's on the nu3001 org  repo.   Same one you forked from.

Mike Wilson
-sent via mobile

**Comment by asidorowicz** [comment]
Found them... I'll start working on that branch instead of my own fork from now on. There was a last commit this morning fixing some stuff in RadioActivity.java
Also, should we put the .idea folder in git ignore? It tends to be machine-specific settings

**Comment by Zaphod-Beeblebrox** [comment]
Yes, we should add the .idea stuff to gitignore.  My first time working
with Android Studio (I always used Eclipse).  Didn't know it would create
those files :)

**Comment by Zaphod-Beeblebrox** [comment]
I've fixed random compile errors in all the apps we've touched so far.  I haven't had time to flash it.  (Maybe tomorrow) to see where we are at.
It looks like we only have BonovoMCU (going to be a BEAR!) and BonovoMusic (will be even worse, since we don't have 1.0.9 to start from.  Is it a new app?)

**Comment by asidorowicz** [comment]
I have added you to my hangout
As a side note, I'm wondering where we could find the JNI compiled stuff in the apk... There may be some important changes there too

**Comment by Zaphod-Beeblebrox** [comment]
OK.  I've not gotten a hangouts request yet.  I have issues with that for some reason ...doesn't always show up.

I have no idea about the jni stuff.  Certainly it's in the APK somewhere, but may already be compiled, such that we won't have access to it.

**Pull request merged**
